on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Dockerのセットアップ
        uses: docker/setup-buildx-action@v1
      - name: Docker Composeでコンテナをビルドして起動
        run: docker compose up --build -d
      - name: Dockerコンテナの状態確認
        run: docker compose ps
      - name: テスト用データベースの作成
        run: docker compose exec -T web rails db:create
      - name: テスト用データベースのマイグレーション
        run: docker compose exec -T web rails db:migrate
      - name: テストの実行
        run: docker compose exec -T web rails test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      HEROKU_APP:     ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL:   ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login to Heroku Container Registry
        run: |
          echo "$HEROKU_API_KEY" | \
          docker login --username=$HEROKU_EMAIL --password-stdin registry.heroku.com
      - name: Build Docker image
        run: docker build -t registry.heroku.com/$HEROKU_APP/web -f Dockerfile.prod .
      - name: Push image to Heroku
        run: docker push registry.heroku.com/$HEROKU_APP/web
      - name: Release image on Heroku
        run: heroku container:release web --app $HEROKU_APP
      - name: Run database migrations
        run: heroku run --app $HEROKU_APP rails db:migrate
