on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build & up containers
        run: docker compose up --build -d
      - name: Prepare test DB
        run: |
          docker compose exec -T web rails db:create
          docker compose exec -T web rails db:migrate
      - name: Run tests
        run: docker compose exec -T web rails test